In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [3]:
data = pd.read_csv("Churn_Modelling.csv")
data.head(5)

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
## Data preprocessing
### Remove the irrelevent colums from the table
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data.tail()

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[5 rows x 11 columns]

In [5]:
## Encode the categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.tail()

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[5 rows x 11 columns]

In [6]:
## One hot encoding "Geography"
from sklearn.preprocessing import OneHotEncoder
onehot_encode_geo = OneHotEncoder()
geo_encoder = onehot_encode_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [7]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
onehot_encode_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encode_geo.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
## Combine the one hot encoder with the original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis=1)
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [11]:
## Save the encodera and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encode_geo, file)

In [12]:
# Divide the dataset into dependent and independent
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [13]:
# Split the training and testing datasets
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Scale thses features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
# save into pickle
with open('scaler_salary.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression Problem statement

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping
import datetime

WARNING:tensorflow:From c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [16]:
X_train.shape[1]

12

In [17]:
## Build our ANN Model
### In regression model at third Dense we dont need to use an activation funtion bcoz it default use linear activation funtion
### And also here in regressionwe use mean_absolute_error loss funtion or mean_squared_error
model = Sequential([
    Dense(64,activation = 'relu', input_shape = (X_train.shape[1],)), ## HL1 Connected with input layer
    Dense(32,activation = 'relu'), ## HL2
    Dense(1) ## Output layer for regression
])

### Compile the model

model.compile(optimizer='adam', loss="mean_absolute_error", metrics=['mae'])

WARNING:tensorflow:From c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
## Set up the tensorflow
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq=1)

In [20]:
## Set up the early stopping
early_stopping_callbacks = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights= True)

In [21]:
## Train the model 
history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test),
    epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callbacks]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 7ms/step - loss: 100378.0625 - mae: 100378.0625 - val_loss: 98514.2344 - val_mae: 98514.2344
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 99609.8750 - mae: 99609.8750 - val_loss: 96957.8594 - val_mae: 96957.8594
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 96892.0547 - mae: 96892.0547 - val_loss: 92961.7578 - val_mae: 92961.7578
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 91563.6719 - mae: 91563.6719 - val_loss: 86353.0859 - val_mae: 86353.0859
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 83800.4141 - mae: 83800.4141 - val_loss: 77763.7891 - val_mae: 77763.7891
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 74672.3516 - mae: 74672.3516 - val_loss: 68904.0547 - val_mae: 68904.0547
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 65842.8516 - mae: 65842.8516 - val_loss: 61186.3867 - val_mae: 61186.3867
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 58838.8438 - mae: 58838.8438 - val_loss: 55747.2852 - val_mae: 55747.2852
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 54310.0859 - mae: 54310.0859 - val_loss: 52704.8867 - val_mae: 52704.8867
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 51879.1094 - mae: 51879.1094 - val_loss: 51490.6758 - val_mae: 51490.6758
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 50881.2383 - mae: 50881.2383 - val_loss: 51104.2812 - val_mae: 51104.2812
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 50499.4492 - mae: 50499.4492 - val_loss: 50947.8633 - val_mae: 50947.8633
Epoch 13/100
250/250 [==============================] - 2s 6ms/step - loss: 50332.8555 - mae: 50332.8555 - val_loss: 50869.8945 - val_mae: 50869.8945
Epoch 14/100
250/250 [==============================] - 1s 6ms/step - loss: 50233.8789 - mae: 50233.8789 - val_loss: 50809.1523 - val_mae: 50809.1523
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 50173.4727 - mae: 50173.4727 - val_loss: 50758.1562 - val_mae: 50758.1562
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 50113.7617 - mae: 50113.7617 - val_loss: 50711.5938 - val_mae: 50711.5938
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 50063.8242 - mae: 50063.8242 - val_loss: 50680.3555 - val_mae: 50680.3555
Epoch 18/100
250/250 [==============================] - 1s 5ms/step - loss: 50023.9336 - mae: 50023.9336 - val_loss: 50642.3281 - val_mae: 50642.3281
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 49981.3008 - mae: 49981.3008 - val_loss: 50613.0703 - val_mae: 50613.0703
Epoch 20/100
250/250 [==============================] - 1s 5ms/step - loss: 49946.7617 - mae: 49946.7617 - val_loss: 50583.6016 - val_mae: 50583.6016
Epoch 21/100
250/250 [==============================] - 2s 6ms/step - loss: 49914.2734 - mae: 49914.2734 - val_loss: 50555.9023 - val_mae: 50555.9023
Epoch 22/100
250/250 [==============================] - 1s 5ms/step - loss: 49882.9648 - mae: 49882.9648 - val_loss: 50541.6250 - val_mae: 50541.6250
Epoch 23/100
250/250 [==============================] - 1s 4ms/step - loss: 49857.1797 - mae: 49857.1797 - val_loss: 50516.4922 - val_mae: 50516.4922
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49833.1367 - mae: 49833.1367 - val_loss: 50504.1484 - val_mae: 50504.1484
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49809.9688 - mae: 49809.9688 - val_loss: 50480.3828 - val_mae: 50480.3828
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49785.3945 - mae: 49785.3945 - val_loss: 50467.2812 - val_mae: 50467.2812
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 49765.6523 - mae: 49765.6523 - val_loss: 50452.7734 - val_mae: 50452.7734
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 49745.6016 - mae: 49745.6016 - val_loss: 50433.8828 - val_mae: 50433.8828
Epoch 29/100
250/250 [==============================] - 1s 4ms/step - loss: 49730.5508 - mae: 49730.5508 - val_loss: 50417.3633 - val_mae: 50417.3633
Epoch 30/100
250/250 [==============================] - 1s 5ms/step - loss: 49714.1406 - mae: 49714.1406 - val_loss: 50404.1289 - val_mae: 50404.1289
Epoch 31/100
250/250 [==============================] - 1s 5ms/step - loss: 49698.2852 - mae: 49698.2852 - val_loss: 50394.2617 - val_mae: 50394.2617
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49682.7617 - mae: 49682.7617 - val_loss: 50386.6719 - val_mae: 50386.6719
Epoch 33/100
250/250 [==============================] - 1s 5ms/step - loss: 49670.2266 - mae: 49670.2266 - val_loss: 50374.9336 - val_mae: 50374.9336
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 49658.4414 - mae: 49658.4414 - val_loss: 50367.9531 - val_mae: 50367.9531
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49651.6719 - mae: 49651.6719 - val_loss: 50363.1836 - val_mae: 50363.1836
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49637.6367 - mae: 49637.6367 - val_loss: 50360.6797 - val_mae: 50360.6797
Epoch 37/100
250/250 [==============================] - 1s 5ms/step - loss: 49625.1758 - mae: 49625.1758 - val_loss: 50361.6328 - val_mae: 50361.6328
Epoch 38/100
250/250 [==============================] - 1s 5ms/step - loss: 49615.9570 - mae: 49615.9570 - val_loss: 50353.7266 - val_mae: 50353.7266
Epoch 39/100
250/250 [==============================] - 1s 6ms/step - loss: 49602.2148 - mae: 49602.2148 - val_loss: 50346.0000 - val_mae: 50346.0000
Epoch 40/100
250/250 [==============================] - 1s 5ms/step - loss: 49593.7891 - mae: 49593.7891 - val_loss: 50341.9492 - val_mae: 50341.9492
Epoch 41/100
250/250 [==============================] - 1s 6ms/step - loss: 49587.3359 - mae: 49587.3359 - val_loss: 50340.4336 - val_mae: 50340.4336
Epoch 42/100
250/250 [==============================] - 1s 5ms/step - loss: 49579.0078 - mae: 49579.0078 - val_loss: 50351.2227 - val_mae: 50351.2227
Epoch 43/100
250/250 [==============================] - 1s 5ms/step - loss: 49565.7539 - mae: 49565.7539 - val_loss: 50339.3867 - val_mae: 50339.3867
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49559.4844 - mae: 49559.4844 - val_loss: 50337.0430 - val_mae: 50337.0430
Epoch 45/100
250/250 [==============================] - 1s 5ms/step - loss: 49551.9297 - mae: 49551.9297 - val_loss: 50326.5195 - val_mae: 50326.5195
Epoch 46/100
250/250 [==============================] - 1s 6ms/step - loss: 49544.4062 - mae: 49544.4062 - val_loss: 50331.9453 - val_mae: 50331.9453
Epoch 47/100
250/250 [==============================] - 1s 6ms/step - loss: 49536.4414 - mae: 49536.4414 - val_loss: 50337.4062 - val_mae: 50337.4062
Epoch 48/100
250/250 [==============================] - 2s 7ms/step - loss: 49528.3828 - mae: 49528.3828 - val_loss: 50334.8945 - val_mae: 50334.8945
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49520.3125 - mae: 49520.3125 - val_loss: 50338.5117 - val_mae: 50338.5117
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49517.4219 - mae: 49517.4219 - val_loss: 50327.6211 - val_mae: 50327.6211
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49511.1602 - mae: 49511.1602 - val_loss: 50320.5273 - val_mae: 50320.5273
Epoch 52/100
250/250 [==============================] - 1s 4ms/step - loss: 49505.6758 - mae: 49505.6758 - val_loss: 50327.1289 - val_mae: 50327.1289
Epoch 53/100
250/250 [==============================] - 1s 5ms/step - loss: 49499.6250 - mae: 49499.6250 - val_loss: 50330.3086 - val_mae: 50330.3086
Epoch 54/100
250/250 [==============================] - 1s 5ms/step - loss: 49492.6562 - mae: 49492.6562 - val_loss: 50332.7734 - val_mae: 50332.7734
Epoch 55/100
250/250 [==============================] - 1s 4ms/step - loss: 49487.9102 - mae: 49487.9102 - val_loss: 50323.5430 - val_mae: 50323.5430
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 49481.7383 - mae: 49481.7383 - val_loss: 50330.4375 - val_mae: 50330.4375
Epoch 57/100
250/250 [==============================] - 1s 4ms/step - loss: 49475.3555 - mae: 49475.3555 - val_loss: 50330.1250 - val_mae: 50330.1250
Epoch 58/100
250/250 [==============================] - 1s 4ms/step - loss: 49471.0742 - mae: 49471.0742 - val_loss: 50330.0742 - val_mae: 50330.0742
Epoch 59/100
250/250 [==============================] - 1s 4ms/step - loss: 49467.2461 - mae: 49467.2461 - val_loss: 50328.0352 - val_mae: 50328.0352
Epoch 60/100
250/250 [==============================] - 1s 4ms/step - loss: 49460.3359 - mae: 49460.3359 - val_loss: 50329.9492 - val_mae: 50329.9492
Epoch 61/100
250/250 [==============================] - 1s 5ms/step - loss: 49457.1914 - mae: 49457.1914 - val_loss: 50328.2812 - val_mae: 50328.2812

In [22]:
## Save the model
model.save('regressionmodel.h5')

c:\Users\KIRUBAK\Desktop\Gen AI\.venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [23]:
## Load tensorboard Extension
%load_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6008 (pid 36788), started 5:13:48 ago. (Use '!kill 36788' to kill it.)

In [26]:
## Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Mae: {test_mae}')

63/63 [==============================] - 0s 3ms/step - loss: 50320.5273 - mae: 50320.5273
Test Mae: 50320.52734375